#!/usr/bin/env python3
# canonical-challenge-prep v1.3.1 (publication standard v1.4)
"""Keep challenge workspaces self-contained and checkable on their own.

Each Challenge must compile on its own, against Mathlib only, so a
Challenge may not import any module of this repository. The trusted vocabulary
of each workspace therefore lives twice:

* ``Vocabulary.lean`` (and/or ``Vocabulary/**/*.lean``): Mathlib-only modules
  that ``Solution.lean`` imports; this is the copy you edit;
* ``Challenge.lean``: a single file whose block between the markers
  ``-- BEGIN GENERATED VOCABULARY`` and ``-- END GENERATED VOCABULARY`` is
  generated from the vocabulary files by ``sync``. Everything after the block
  (the ``sorry`` stubs of the compared theorems) is written by hand.

Comparator compares every declaration reached from a compared statement by name
and by value, so the two copies must agree exactly; ``check`` enforces that.

Split vocabulary (opt-in, not self-contained): concatenating several vocabulary
modules into one file can change the names of Lean's auxiliary proofs (they are
cached per module, keyed by type), so a Challenge that restates a multi-module
library may not match it by value. Such a workspace marks Challenge.lean with a
line starting ``-- challenge-prep: split vocabulary`` and imports its
``Vocabulary.*`` modules directly instead of carrying a generated block.
``sync`` and ``init`` skip it; ``check`` requires that Challenge.lean imports
only Lean core, Mathlib or this workspace's vocabulary modules, that it opens
``@[expose] public section`` after its imports (otherwise the module system
makes the stubs private and they vanish from the compared environment; a
generated block provides this line), and that the vocabulary itself is
Mathlib-only.

Commands (run from the repository root):

  challenge-prep.py sync  [WORKSPACE ...]   regenerate the vocabulary block
  challenge-prep.py init  WORKSPACE ...     convert an old Challenge.lean (with
                                          local imports) to the marker layout
  challenge-prep.py check [--root DIR]      every check below; non-zero exit on
                                          any failure

``check`` covers:
  1. every regular .lean file (except lakefile.lean) starts with the ``module``
     header, using the verifier's rule: only whitespace, ``--`` comments and
     plain ``/- -/`` comments may precede it (not ``/--`` or ``/-!``);
  2. no .lean file exceeds 10,000 lines, and no .lean path is a symlink;
  3. in each challenges/*/ workspace (a directory holding only build output such
     as ``.lake/``, left behind after ``git rm``, is not a workspace), the
     vocabulary block of Challenge.lean equals what ``sync`` would generate,
     Challenge.lean has no other imports, and every import of the vocabulary
     is Lean core or Mathlib (split-vocabulary workspaces: see above);
  4. Challenge.lean is at most 1,000 lines and 100 KiB (warning above 300 lines
     or 32 KiB, the preferred audit surface).
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

BEGIN = "-- BEGIN GENERATED VOCABULARY"
END = "-- END GENERATED VOCABULARY"
BEGIN_LINE = (BEGIN + ": generated by scripts/challenge-prep.py from the Vocabulary modules;"
              " edit those, then run `python3 scripts/challenge-prep.py sync`.")
EXPOSE = "@[expose] public section"
SPLIT_MARKER = "-- challenge-prep: split vocabulary"

# Import roots allowed in a Challenge closure: Lean core and the pinned Mathlib
# closure (which includes Mathlib's own dependencies).
ALLOWED_IMPORT_ROOTS = {
    "Init", "Std", "Lean", "Mathlib", "Batteries", "Aesop", "Qq", "Plausible",
    "ProofWidgets", "LeanSearchClient", "ImportGraph",
}
MAX_SOURCE_LINES = 10_000
CHALLENGE_MAX_LINES, CHALLENGE_MAX_BYTES = 1_000, 100 * 1024
CHALLENGE_SOFT_LINES, CHALLENGE_SOFT_BYTES = 300, 32 * 1024

IMPORT_RE = re.compile(r"^(?:public\s+)?(?:meta\s+)?import\s+(\S+)\s*$")
BUILD_DIRS = {".lake"}
COMMENT_MARKER = re.compile(r"/-|-/")
ID_CONT = re.compile(r"[A-Za-z0-9_'!?À-ɏͰ-Ͽ₀-ₜ.]")


class Failure(Exception):
    pass


# --- module header (mirrors the verifier's has_module_header) -----------------

def has_module_header(text: str) -> bool:
    i = 0
    while i < len(text):
        if text[i] in " \r\n":
            i += 1
        elif text.startswith("--", i):
            end = text.find("\n", i + 2)
            i = len(text) if end < 0 else end + 1
        elif text.startswith("/-", i) and not text.startswith(("/--", "/-!"), i):
            i += 3
            depth = 1
            while depth:
                m = COMMENT_MARKER.search(text, i)
                if m is None:
                    return False
                depth += 1 if m.group() == "/-" else -1
                i = m.end()
        else:
            return text.startswith("module", i) and ID_CONT.match(text, i + 6) is None
    return False


def physical_lines(text: str) -> int:
    return text.count("\n") + int(bool(text) and not text.endswith("\n"))


# --- vocabulary parsing ---------------------------------------------------------

def split_header(path: Path) -> tuple[list[str], list[str]]:
    """Return (import module names, body lines) of a vocabulary module."""
    lines = path.read_text(encoding="utf-8").splitlines()
    if not has_module_header("\n".join(lines)):
        raise Failure(f"{path}: vocabulary file must start with `module`")
    imports: list[str] = []
    i, seen_module, depth = 0, False, 0
    while i < len(lines):
        s = lines[i].strip()
        if depth > 0:
            depth += len(re.findall(r"/-", s)) - len(re.findall(r"-/", s))
            i += 1
            continue
        if s == "" or s.startswith("--"):
            i += 1
            continue
        if s.startswith("/-") and not s.startswith(("/--", "/-!")):
            depth = len(re.findall(r"/-", s)) - len(re.findall(r"-/", s))
            i += 1
            continue
        if not seen_module and s == "module":
            seen_module = True
            i += 1
            continue
        m = IMPORT_RE.match(s)
        if m:
            imports.append(m.group(1))
            i += 1
            continue
        break
    body = lines[i:]
    return imports, body


SCOPE_OPEN = re.compile(r"^(?:noncomputable\s+)?(?:@\[[^\]]*\]\s*)?(?:public\s+)?(namespace|section)(?:\s+(\S+))?\s*$")
SCOPE_END = re.compile(r"^end(?:\s+(\S+))?\s*$")


def open_namespaces(lines: list[str]) -> list[str]:
    """Namespaces still open at the end of a body (comments are not parsed).

    Anonymous or named sections left open are harmless, since they do not change
    declaration names; an open namespace would rename the next file's declarations.
    """
    stack: list[tuple[str, str | None]] = []
    for ln in lines:
        s = ln.strip()
        if m := SCOPE_OPEN.match(s):
            stack.append((m.group(1), m.group(2)))
        elif (m := SCOPE_END.match(s)) and stack:
            stack.pop()
    return [name or "" for kind, name in stack if kind == "namespace"]


def vocabulary_files(ws: Path) -> dict[str, Path]:
    files: dict[str, Path] = {}
    if (ws / "Vocabulary.lean").is_file():
        files["Vocabulary"] = ws / "Vocabulary.lean"
    vdir = ws / "Vocabulary"
    if vdir.is_dir():
        for p in sorted(vdir.rglob("*.lean")):
            rel = p.relative_to(ws).with_suffix("")
            files[".".join(rel.parts)] = p
    return files


def generate_block(ws: Path) -> list[str]:
    files = vocabulary_files(ws)
    if not files:
        raise Failure(f"{ws}: no Vocabulary.lean or Vocabulary/*.lean")
    parsed = {name: split_header(p) for name, p in files.items()}
    order: list[str] = []
    state: dict[str, int] = {}

    def visit(name: str) -> None:
        if state.get(name) == 2:
            return
        if state.get(name) == 1:
            raise Failure(f"{ws}: import cycle through {name}")
        state[name] = 1
        for imp in parsed[name][0]:
            if imp in files:
                visit(imp)
        state[name] = 2
        order.append(name)

    for name in sorted(files):
        visit(name)

    external: list[str] = []
    bodies: list[str] = []
    for name in order:
        imports, body = parsed[name]
        for imp in imports:
            if imp in files:
                continue
            if imp.split(".")[0] not in ALLOWED_IMPORT_ROOTS:
                raise Failure(f"{files[name]}: import {imp} is outside Lean core/Mathlib")
            if imp not in external:
                external.append(imp)
        stripped = [ln for ln in body if ln.strip() != EXPOSE]
        if len(stripped) == len(body):
            raise Failure(f"{files[name]}: missing `{EXPOSE}` after the imports")
        if opened := open_namespaces(stripped):
            raise Failure(f"{files[name]}: namespace {', '.join(opened)} left open; close it so"
                          " that concatenated files keep their declaration names")
        while stripped and stripped[0].strip() == "":
            stripped.pop(0)
        while stripped and stripped[-1].strip() == "":
            stripped.pop()
        rel = files[name].relative_to(ws).as_posix()
        bodies += ["", f"-- from {rel}"] + stripped
    block = [BEGIN_LINE] + [f"public import {imp}" for imp in external]
    block += ["", EXPOSE] + bodies + [END]
    return block


def challenge_parts(path: Path) -> tuple[list[str], list[str], list[str]]:
    lines = path.read_text(encoding="utf-8").splitlines()
    starts = [i for i, ln in enumerate(lines) if ln.startswith(BEGIN)]
    ends = [i for i, ln in enumerate(lines) if ln.startswith(END)]
    if len(starts) != 1 or len(ends) != 1 or ends[0] < starts[0]:
        raise Failure(f"{path}: needs exactly one {BEGIN!r} ... {END!r} block")
    return lines[:starts[0]], lines[starts[0]:ends[0] + 1], lines[ends[0] + 1:]


def workspaces(root: Path, names: list[str]) -> list[Path]:
    if names:
        return [root / "challenges" / n if not (root / n).is_dir() else root / n for n in names]
    # A directory with nothing but build output (e.g. `.lake/` left behind after
    # `git rm` of a workspace) or Finder litter is not a workspace.
    return sorted(p for p in (root / "challenges").glob("*/")
                  if p.is_dir() and any(c.name not in BUILD_DIRS | {".DS_Store"} for c in p.iterdir()))


def is_split(ch: Path) -> bool:
    return any(ln.startswith(SPLIT_MARKER) for ln in ch.read_text(encoding="utf-8").splitlines())


# --- commands ---------------------------------------------------------------------

def cmd_sync(root: Path, names: list[str]) -> int:
    for ws in workspaces(root, names):
        ch = ws / "Challenge.lean"
        if is_split(ch):
            print(f"skip {ch.relative_to(root)}: split vocabulary")
            continue
        head, _, tail = challenge_parts(ch)
        new = "\n".join(head + generate_block(ws) + tail) + "\n"
        if ch.read_text(encoding="utf-8") != new:
            ch.write_text(new, encoding="utf-8")
            print(f"updated {ch.relative_to(root)}")
    return 0


def cmd_init(root: Path, names: list[str]) -> int:
    if not names:
        raise Failure("init needs explicit workspace names")
    for ws in workspaces(root, names):
        ch = ws / "Challenge.lean"
        text = ch.read_text(encoding="utf-8")
        if is_split(ch):
            print(f"skip {ch.relative_to(root)}: split vocabulary")
            continue
        if BEGIN in text:
            print(f"skip {ch.relative_to(root)}: already has the marker block")
            continue
        body = [ln for ln in text.splitlines()
                if not IMPORT_RE.match(ln.strip()) and ln.strip() != "module"]
        while body and body[0].strip() == "":
            body.pop(0)
        new = "\n".join(["module", ""] + generate_block(ws) + [""] + body) + "\n"
        ch.write_text(new, encoding="utf-8")
        print(f"initialised {ch.relative_to(root)}; review the stubs below the block")
    return 0


def lean_files(root: Path) -> list[Path]:
    out = []
    for d, subdirs, names in os.walk(root, followlinks=False):
        subdirs[:] = sorted(s for s in subdirs if s not in {".git"} | BUILD_DIRS)
        out += [Path(d) / n for n in sorted(names) if n.endswith(".lean")]
    return out


def cmd_check(root: Path) -> int:
    failures: list[str] = []
    warnings: list[str] = []
    notes: list[str] = []
    for p in lean_files(root):
        rel = p.relative_to(root).as_posix()
        if p.is_symlink():
            failures.append(f"{rel}: .lean symlinks are not accepted")
            continue
        text = p.read_text(encoding="utf-8", errors="replace")
        if physical_lines(text) > MAX_SOURCE_LINES:
            failures.append(f"{rel}: more than {MAX_SOURCE_LINES} lines")
        if p.name != "lakefile.lean" and not has_module_header(text):
            failures.append(f"{rel}: does not start with the `module` header")
    for ws in workspaces(root, []):
        rel = ws.relative_to(root).as_posix()
        ch = ws / "Challenge.lean"
        if not ch.is_file():
            failures.append(f"{rel}: no Challenge.lean")
            continue
        try:
            if is_split(ch):
                generate_block(ws)  # validates the vocabulary: Mathlib-only imports, exposure, namespaces
                vocab = vocabulary_files(ws)
                for ln in ch.read_text(encoding="utf-8").splitlines():
                    m = IMPORT_RE.match(ln.strip())
                    if m and m.group(1) not in vocab and m.group(1).split(".")[0] not in ALLOWED_IMPORT_ROOTS:
                        failures.append(f"{rel}/Challenge.lean: import {m.group(1)} is neither Lean core/Mathlib"
                                        " nor a vocabulary module of this workspace")
                    if BEGIN in ln or END in ln:
                        failures.append(f"{rel}/Challenge.lean: split vocabulary and a generated block")
                if not any(ln.strip() == EXPOSE for ln in ch.read_text(encoding="utf-8").splitlines()):
                    failures.append(f"{rel}/Challenge.lean: split vocabulary needs `{EXPOSE}` after the"
                                    " imports, or the stubs are private and absent from the compared environment")
                notes.append(f"{rel}: split vocabulary (Challenge.lean imports its Vocabulary modules;"
                             " not self-contained)")
            else:
                head, block, tail = challenge_parts(ch)
                if block != generate_block(ws):
                    failures.append(f"{rel}/Challenge.lean: vocabulary block is out of date"
                                    " (run `python3 scripts/challenge-prep.py sync`)")
                for ln in head + tail:
                    if IMPORT_RE.match(ln.strip()):
                        failures.append(f"{rel}/Challenge.lean: import outside the generated block: {ln.strip()}")
        except Failure as e:
            failures.append(str(e))
        data = ch.read_bytes()
        n = physical_lines(data.decode("utf-8", errors="replace"))
        if n > CHALLENGE_MAX_LINES or len(data) > CHALLENGE_MAX_BYTES:
            failures.append(f"{rel}/Challenge.lean: {n} lines / {len(data)} bytes exceeds 1,000 lines / 100 KiB")
        elif n > CHALLENGE_SOFT_LINES or len(data) > CHALLENGE_SOFT_BYTES:
            warnings.append(f"{rel}/Challenge.lean: {n} lines / {len(data)} bytes exceeds the preferred 300 lines / 32 KiB")
    for note in notes:
        print(f"NOTE: {note}", file=sys.stderr)
    for w in warnings:
        print(f"WARN: {w}", file=sys.stderr)
    for f in failures:
        print(f"FAIL: {f}", file=sys.stderr)
    if failures:
        print(f"challenge-prep check FAILED with {len(failures)} failure(s)", file=sys.stderr)
        return 1
    print("challenge-prep check passed")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", choices=["sync", "init", "check"])
    ap.add_argument("workspaces", nargs="*")
    ap.add_argument("--root", default=".", help="repository root (default: current directory)")
    a = ap.parse_args()
    root = Path(a.root).resolve()
    try:
        if a.command == "sync":
            return cmd_sync(root, a.workspaces)
        if a.command == "init":
            return cmd_init(root, a.workspaces)
        return cmd_check(root)
    except Failure as e:
        print(f"FAIL: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
